spring.application.name=AMS
server.port=8081

#Local Database
spring.datasource.url=jdbc:mysql://localhost:3306/AMS
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
